config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :courses do
    get 'index'
    post 'index', to: 'courses#create', as: 'create'
    put 'index', to: 'courses#update', as: 'update'
    delete 'index', to: 'courses#destroy', as: 'delete'
    get 'navigation'
    post 'navigation', to: 'teams#create', as: 'create_team'
  end
  resources :teams do
    put 'update', to: 'teams#update', as: 'update'
  end
  resources :students do
    put 'edit', to: 'students#update'
  end
  resources :projects do
    get 'add-team', to: 'projects#create_project_team'
    post 'add-team', to: 'projects#create_project_team', as: 'create_team'
    delete 'remove-student', to: 'projects#remove_team', as: 'remove_team'
    get 'update-project', to: 'projects#update'
    patch 'update-project', to: 'projects#update', as: 'update'
    get 'change_average', to: 'projects#set_avg_score'
    patch 'change_average', to: 'projects#set_avg_score', as: 'update_avg'
  end
  resources :evaluations do
  end
  resources :users

  root 'sessions#new'

  get '/search', to: 'students#search'
  post '/search', to: 'students#create'
  # ----------------------- login ----------------------------
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # ------------------------ logout ---------------------------
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  # ----------------------- sign up ----------------------------
  get '/signupstudents', to: 'users#newStudent'
  post '/signupstudents', to: 'users#createStudent'
  get '/signupprofessors', to: 'users#newProfessor'
  post '/signupprofessors', to: 'users#createProfessor'
  # ----------------------- evaluation ----------------------------
  get 'static_pages', to: 'static_pages#dashboard', as: :student_dashboard
  get 'static_pages/view_evaluations', to: 'static_pages#view_evaluations', as: :view_evaluations
  # ----------------------- admin ----------------------------
  post '/:id/search', to: 'students#create'
  post '/addstudent', to: 'students#createFromTeam'

  get '/:id/students/22/edit', to: 'students#create'
  get '/courses/:id/course_navigation', to: 'courses#navigation'
  get '/courses/:id/course_navigation/new_team', to: 'teams#new'
  get '/courses/:id/course_navigation/new_student', to: 'students#new'
  # route to remove student from team - teams/show.html.erb
  delete '/student/:id', to: 'students#destroy', as: 'remove_student'
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

# static_pages controller
class StaticPagesController < ApplicationController
  def dashboard
    @user = current_user
    # each user can be students in many diff course
    @students = @user.students
  end

  def view_evaluations
    @for_student = Student.find(params[:for_student])
    @project = Project.find(params[:project_id])
  end
end

app/views/static_pages/dashboard.html.erb
<h2 class="text-center my-5">Student Dashboard for <%= @user.name %></h2>
<div class="table-responsive">
  <table class="table table-light table-striped table-bordered rounded text-center">
    <thead>
      <tr>
        <th scope="col" class="col-1">Project</th>
        <th scope="col" class="col-1">Action</th>
        <th scope="col" class="col-1">Team</th>
        <th scope="col" class="col-1">Class</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student|%>
        <% if !student.team.nil? %>
          <% ProjectTeam.where(team_id: student.team_id).each do |project_team| %>
            <% project = Project.find(project_team.project_id) %>
            <tr>
              <td><%= project.project_name %></td>
              <% evaluation = Evaluation.find_by(project_id: project.id, team_id: project_team.team_id) %>
              <% if Evaluation.where(project_id: project.id, team_id: project_team.team_id).find_by(score: nil, comment: nil).nil? %>
                <%# all assigned evaluations for this project has been filled by this team %>
                <td><%= link_to 'View Evaluations',  view_evaluations_path(project_id: project.id, for_student: student.id) %></td>
              <% elsif Evaluation.where(project_id: project.id, by_student: student.id).find_by(score: nil, comment: nil).nil? %>
                <%# all evaluations for this project has been filled by this student %>
                <td><%= link_to '', "#", class:"visually-hidden" %></td>
              <% else %>
                <%# there is evaluations for this project still not filled by this student %>
                <td><%= link_to 'Start Evaluation', evaluations_path(project_id: project.id, by_student: student.id) %></td>
              <% end %>
              <td><%= student.team.team_name %></td>
              <td><%= Course.find(student.team.course_id).course_name %></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/static_pages/view.erb
<h2 class="text-center m-5">Evaluations for <%= @project.project_name %></h2>
<table class="table table-light table-striped table-bordered rounded text-center">
  <thead>
    <tr>
      <th scope="col" class="col-1">Score</th>
      <th scope="col" class="col-2">Comments</th>
    </tr>
  </thead>
  <tbody>
    <% @student.team.evaluations.each do |evaluation|%>
      <tr>
        <td><%= evaluation.score %></td>
        <td><%= evaluation.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/static_pages/view_evaluations.html.erb
<h2 class="text-center m-5">Evaluations for <%= @project.project_name %></h2>
<table class="table table-light table-striped table-bordered rounded text-center">
  <thead>
    <tr>
      <th scope="col" class="col-1">Score</th>
      <th scope="col" class="col-2">Comments</th>
    </tr>
  </thead>
  <tbody>
    <% Evaluation.where(for_student: @for_student.id, project_id: @project.id).each do |evaluation|%>
      <tr>
        <td><%= evaluation.score %></td>
        <td><%= evaluation.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '&#8592; Back'.html_safe, "/static_pages", class:"btn btn-primary btn p-2 rounded col-md-1 col-12 mb-5" %>