config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :courses do
    get 'index'
    post 'index', to: 'courses#create', as: 'create'
    put 'index', to: 'courses#update', as: 'update'
    delete 'index', to: 'courses#destroy', as: 'delete'
    get 'navigation'
    post 'navigation', to: 'teams#create', as: 'create_team'
  end
  resources :teams do
    put 'update', to: 'teams#update', as: 'update'
  end
  resources :students do
    put 'edit', to: 'students#update'
  end
  resources :projects do
    get 'add-team', to: 'projects#create_project_team'
    post 'add-team', to: 'projects#create_project_team', as: 'create_team'
    delete 'remove-student', to: 'projects#remove_team', as: 'remove_team'
    get 'update-project', to: 'projects#update'
    patch 'update-project', to: 'projects#update', as: 'update'
    get 'change_average', to: 'projects#set_avg_score'
    patch 'change_average', to: 'projects#set_avg_score', as: 'update_avg'
  end
  resources :evaluations do
  end
  resources :users

  root 'sessions#new'

  get '/search', to: 'students#search'
  post '/search', to: 'students#create'
  # ----------------------- login ----------------------------
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # ------------------------ logout ---------------------------
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  # ----------------------- sign up ----------------------------
  get '/signupstudents', to: 'users#newStudent'
  post '/signupstudents', to: 'users#createStudent'
  get '/signupprofessors', to: 'users#newProfessor'
  post '/signupprofessors', to: 'users#createProfessor'
  # ----------------------- evaluation ----------------------------
  get 'static_pages', to: 'static_pages#dashboard', as: :student_dashboard
  get 'static_pages/view_evaluations', to: 'static_pages#view_evaluations', as: :view_evaluations
  # ----------------------- admin ----------------------------
  post '/:id/search', to: 'students#create'
  post '/addstudent', to: 'students#createFromTeam'

  get '/:id/students/22/edit', to: 'students#create'
  get '/courses/:id/course_navigation', to: 'courses#navigation'
  get '/courses/:id/course_navigation/new_team', to: 'teams#new'
  get '/courses/:id/course_navigation/new_student', to: 'students#new'
  # route to remove student from team - teams/show.html.erb
  delete '/student/:id', to: 'students#destroy', as: 'remove_student'
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

# controller for courses
class CoursesController < ApplicationController
  before_action :set_course, only: %i[update destroy]

  # GET /courses
  # GET /courses.json
  def index
    professors = User.find(current_user.id).professors
    @courses = []
    professors.each do |professor|
      @courses << Course.find(professor.course_id) unless professor.course_id.nil?
    end
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @user = User.find(current_user.id)

    if @course.save
      # tag professor to a new course
      Professor.create user_id: current_user.id, course_id: @course.id
      # delete all professor for this user without a course_id
      @user.professors.all.where(course_id: nil).destroy_all
      flash[:success] = "Course #{@course.course_name} was successfully created."
    else
      # create fails
      flash[:danger] = "Course could not be created. #{@course.errors.full_messages[0]}"
    end
    redirect_to courses_url
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    old_name = @course.course_name
    if @course.update(course_params)
      flash[:success] = "#{old_name} was successfully updated to #{@course.course_name}."
    else
      flash[:danger] = "#{@course.course_name} could not be updated. #{@course.errors.full_messages[0]}"
    end
    redirect_to courses_url
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    flash[:success] = "#{@course.course_name} was successfully deleted."
    @course.destroy
    redirect_to courses_url
  end

  def navigation
    # @team = Team.new
    @course = Course.find(params[:id])
    @teams = Team.all.where(course_id: @course.id)
    # get students in the course
    @students = []
    Course.find(@course.id).teams.all.each do |team|
      team.students.each do |student|
        @students << student
      end
    end
    # create evaluations if not already created
    create_evaluations_for_all_project_teams(params[:id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:course_num, :course_name)
  end
end

app/views/courses/index_partials/_create_course_form.html.erb
<%= form_with(url: create_courses_path, model: @course, class:"row d-flex justify-content-center gy-3") do |form| %>
  <div class="col-xl-5 col-md-6 col-12">
    <input name="course[course_name]" type="text" class="form-control form-control-lg" placeholder="Course Name" aria-label="Course Name">
  </div>
  <div class="col-xl-5 col-md-6 col-12">
    <input name="course[course_num]" type="text" class="form-control form-control-lg" placeholder="Course Number" aria-label="Course Number">
  </div>
  <div class="actions col-xl-2 col-12">
    <%= form.submit "Create Course", class: "btn btn-primary btn-lg p-2 rounded" %>
  </div>
<% end %>

app/views/courses/index_partials/_update_course_form.erb
<%= form_with(url: update_courses_path(id: course.id), method: 'put') do |form| %>
  <div class="row">
    <div class="col">
      <%= form.text_field :"course[course_name]", class:"form-control form-control", placeholder:"Course Name", value: course.course_name, id:nil, "aria-label":"Course Name" %>
    </div>
    <div class="col">
      <%= form.text_field :"course[course_num]", class:"form-control form-control", placeholder:"Course Number", value: course.course_num, id:nil, "aria-label":"Course Number" %>
    </div>
    <div class="actions col">
      <%= form.submit "Update", class: "btn btn-primary btn p-2 rounded" %>
    </div>
  </div>
<% end %>