config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :courses do
    get 'index'
    post 'index', to: 'courses#create', as: 'create'
    put 'index', to: 'courses#update', as: 'update'
    delete 'index', to: 'courses#destroy', as: 'delete'
    get 'navigation'
    post 'navigation', to: 'teams#create', as: 'create_team'
  end
  resources :teams do
    put 'update', to: 'teams#update', as: 'update'
  end
  resources :students do
    put 'edit', to: 'students#update'
  end
  resources :projects do
    get 'add-team', to: 'projects#create_project_team'
    post 'add-team', to: 'projects#create_project_team', as: 'create_team'
    delete 'remove-student', to: 'projects#remove_team', as: 'remove_team'
    get 'update-project', to: 'projects#update'
    patch 'update-project', to: 'projects#update', as: 'update'
    get 'change_average', to: 'projects#set_avg_score'
    patch 'change_average', to: 'projects#set_avg_score', as: 'update_avg'
  end
  resources :evaluations do
  end
  resources :users

  root 'sessions#new'

  get '/search', to: 'students#search'
  post '/search', to: 'students#create'
  # ----------------------- login ----------------------------
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # ------------------------ logout ---------------------------
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  # ----------------------- sign up ----------------------------
  get '/signupstudents', to: 'users#newStudent'
  post '/signupstudents', to: 'users#createStudent'
  get '/signupprofessors', to: 'users#newProfessor'
  post '/signupprofessors', to: 'users#createProfessor'
  # ----------------------- evaluation ----------------------------
  get 'static_pages', to: 'static_pages#dashboard', as: :student_dashboard
  get 'static_pages/view_evaluations', to: 'static_pages#view_evaluations', as: :view_evaluations
  # ----------------------- admin ----------------------------
  post '/:id/search', to: 'students#create'
  post '/addstudent', to: 'students#createFromTeam'

  get '/:id/students/22/edit', to: 'students#create'
  get '/courses/:id/course_navigation', to: 'courses#navigation'
  get '/courses/:id/course_navigation/new_team', to: 'teams#new'
  get '/courses/:id/course_navigation/new_student', to: 'students#new'
  # route to remove student from team - teams/show.html.erb
  delete '/student/:id', to: 'students#destroy', as: 'remove_student'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :course, optional: true

  has_many :teams, through: :course
  has_many :project_teams, dependent: :delete_all

  validates :project_name, presence: true
  validates :course_id, presence: true
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# projects controller
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects
  # GET /projects.json
  def index
    # get all projects for a particular course
    @projects = Project.all.where(course_id: params[:course_id])
    # create evaluations if not already created
    create_evaluations_for_all_project_teams(params[:course_id])
    professors = User.find(current_user.id).professors
    @courses = []
    professors.each do |professor|
      @courses << Course.find(professor.course_id) unless professor.course_id.nil?
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:success] = "#{@project.project_name} was successfully created."
      # redirects to the correct course project page
      redirect_to projects_url(course_id: @project.course_id)
    else
      flash[:danger] = "Project could not be created. #{@project.errors.full_messages[0]}"
      redirect_to projects_url(course_id: params[:course_id])
    end
  end

  def set_avg_score
    @evaluation = Evaluation.find_by(project_id: params[:project_id], team_id: params[:team_id],
                                     by_professor: true, for_student: params[:for_student])

    user = Student.find(params[:for_student]).user
    if params[:score].to_i <= 0
      flash[:danger] = "Average score for #{user.name} cannot be 0 or less."
    elsif params[:score].to_i > 10
      flash[:danger] = "Average score for #{user.name} cannot more than 10."
    elsif @evaluation.update(params.permit(:score))
      flash[:success] = "Average score for #{user.name} has been changed to #{params[:score]}."
    end
    redirect_to projects_url(course_id: params[:course_id])
  end

  def create_project_team
    @project_team = ProjectTeam.new(project_team_params)
    project = Project.find(@project_team.project_id)
    team = Team.find(@project_team.team_id)

    if ProjectTeam.find_by(project_id: project.id, team_id: team.id).present?
      # team added more than once to the same project
      flash[:danger] =  "Unable to add team. Team #{team.team_name} has already been added to #{project.project_name}."
    elsif @project_team.save
      # create evaluations for the team for this project
      helpers.create_evaluations_for_project(@project_team)
      flash[:success] = "#{team.team_name} was successfully added to #{project.project_name}."
    end
    redirect_to projects_url(course_id: project.course_id)
  end

  def update
    old_name = @project.project_name
    if @project.update(project_params)
      flash[:success] = "#{old_name} was successfully updated to #{@project.project_name}."
    end
    redirect_to projects_url(course_id: @project.course_id)
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    flash[:success] = "#{@project.project_name} was successfully deleted."
    course_id = @project.course_id
    # deletes all evaluations for this project
    Evaluation.where(project_id: @project.id).destroy_all
    @project.destroy
    redirect_to projects_url(course_id: course_id)
  end

  def remove_team
    project_team = ProjectTeam.find_by(project_id: params[:project_id], team_id: params[:team])
    team = Team.find(project_team.team_id)
    project = Project.find(project_team.project_id)
    flash[:success] = "#{team.team_name} was successfully removed from #{project.project_name}."
    # delete all evaluations related to this team in the project
    Evaluation.where(project_id: params[:project_id], team_id: params[:team]).destroy_all
    # remove team from project
    project_team.destroy
    redirect_to projects_url(course_id: params[:course_id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:project_name, :course_id)
  end

  # Only allow a list of trusted parameters through.
  def project_team_params
    params.permit(:project_id, :team_id)
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

# helper methods for projects
module ProjectsHelper
  # do not create the evaluation if it is already created
  def create_evaluation(project_id, team_id, for_student_id, by_student_id, is_assigned)
    unless Evaluation.all.find_by(project_id: project_id, team_id: team_id, for_student: for_student_id,
                                  by_student: by_student_id).present?

      Evaluation.create project_id: project_id, team_id: team_id, for_student: for_student_id,
                        by_student: by_student_id, score: nil, comment: nil,
                        is_assigned: is_assigned, by_professor: false
    end
  end

  # create blank evaluations for each student for 1 project.
  def create_evaluations_for_project(project_team)
    project_id = project_team.project_id
    team_id = project_team.team_id

    Student.where(team_id: team_id).each do |by_student|
      Student.where(team_id: team_id).where.not(id: by_student.id).each do |for_student|
        # create evaluation for student
        create_evaluation project_id, team_id, for_student.id, by_student.id, true
        # create evaluation for professor
        next if Evaluation.where(project_id: project_id, team_id: team_id, for_student: for_student.id,
                                 is_assigned: false, by_professor: true).present?

        Evaluation.create project_id: project_id, team_id: team_id, for_student: for_student.id,
                          is_assigned: false, by_professor: true
      end
    end
  end

  # create blank evaluations for each project.
  def create_evaluations_for_all_project_teams(course_id)
    Course.find(course_id).projects.each do |project|
      project.project_teams.each do |project_team|
        create_evaluations_for_project(project_team)
        avg_score_of_all_students(project_team)
      end
    end
  end

  def get_avg_score_of_student(evaluation)
    total_score = 0
    num_of_score = 0
    student_evaluations = Evaluation.where(project_id: evaluation.project_id, team_id: evaluation.team_id,
                                           for_student: evaluation.for_student, by_professor: false)
    # calculate avg if all evluations for the student have been filled
    if student_evaluations.where(score: nil, comment: nil).empty?
      student_evaluations.where.not(score: nil).each do |eval|
        total_score += eval.score.to_i
        num_of_score += 1
      end
      total_score / num_of_score unless num_of_score.zero?
    end
  end

  def avg_score_of_all_students(project_team)
    prof_eval = Evaluation.where(project_id: project_team.project_id, team_id: project_team.team_id,
                                 by_professor: true, score: nil)
    prof_eval.each do |evaluation|
      # each evaluation is for a different student
      evaluation.score = get_avg_score_of_student evaluation
      evaluation.save
    end
  end
end

app/views/projects/project_partials/_add_team.erb
<%= form_with(url: project_create_team_path(project_id: project.id), class:"row my-3 justify-content-center g-3") do |form| %>
  <div class="actions col-xl-7 col-9">
    <select class="form-select form-select-lg" aria-label="Select a team" name="team_id" required>
      <option value="">Select a team</option>
      <% Team.all.where(course_id: params[:course_id]).each do |team| %>
        <option value=<%= team.id %>><%= team.team_name %></option>
      <% end %>
    </select>
  </div>
  <%= form.hidden_field :project_id, value: project.id, id:nil %>
  <div class="actions col-xl-2 col-9">
    <%= form.submit "Add Team", class: "btn btn-primary btn-lg p-2 rounded" %>
  </div>
<% end %>

app/views/projects/project_partials/_avg_score.erb
<%= form_with(model:@evaluation, method:'patch', url: project_update_avg_path(id:project.id, project_id: project.id, team_id: team.id, for_student:student.id, course_id: project.course_id)) do |form| %>
  <div class='form-group'>
    <% unless prof_eval.nil? %>
      <%= form.text_field :score, class:"form-control m-auto", placeholder:prof_eval.score, value: prof_eval.score, onchange: 'this.form.submit()', id:nil, "aria-label":"Average Score" %>
    <% end %>
  </div>
<% end %>

app/views/projects/project_partials/_create-project-form.html.erb
<%= form_with(model: @project, class:"row g-3", url: "/projects?course_id=#{params[:course_id]}") do |form| %>
  <div class="col-xl-5 col-md-6 col-12">
    <input name="project[project_name]" type="text" class="form-control  form-control-lg" placeholder="Project Name" aria-label="Project Name" >
  </div>
  <div class="col-xl-5 col-md-6 col-12">
    <select name="project[course_id]" class="form-select form-select-lg col" aria-label="Select a course" required>
      <option value="">Select a course</option>
      <% @courses.each do |course|%>
        <option value=<%= course.id%>><%= course.course_name %></option>
      <% end %>
    </select>
  </div>
  <div class="actions col-xl-2 col-12 mb-3">
    <%= form.submit "Create Project", class: "btn btn-primary btn-lg p-2 rounded" %>
  </div>
<% end %>

app/views/projects/project_partials/_evaluations-for-a-team.erb
<% student_rowspan = get_student_rowspan team %>
<% team_rowspan = get_team_rowspan team, project %>
<% if team.students.length > 2 %>
  <tr>
    <td rowspan=<%= team_rowspan %> class="align-middle"><%= team.team_name %></td>
  </tr>
  <% team.students.each do |student| %>
    <tr>
      <td rowspan=<%= student_rowspan + 1 %> class="align-middle">Evaluations for <%= student.user.name %></td>
    </tr>
    <tr>
      <% prof_eval = Evaluation.where.not(score: nil).find_by(project_id: project.id, team_id: team.id, for_student: student.id, by_professor: true)%>
      <td rowspan=<%= student_rowspan %> class="align-middle">
        <%# form to change avg. score %>
        <%= render 'projects/project_partials/avg_score', prof_eval: prof_eval, project: project, team: team, student: student%>
      </td>
    </tr>
    <% team.evaluations.where(project_id: project.id).where.not(by_student: nil).each do |evaluation| %>
      <% if evaluation.for_student == student.id %>
        <%= render 'projects/project_partials/student_evaluation_row', evaluation: evaluation %>
      <% end %>
    <% end %>
  <% end %>
<% elsif team.students.length > 1 %>
  <tr>
    <td rowspan=3 class="align-middle"><%= team.team_name %></td>
  </tr>
  <% team.students.each do |student| %>
    <tr>
      <td class="align-middle">Evaluations for <%= student.user.name %></td>
      <% prof_eval = Evaluation.where.not(score: nil).find_by(project_id: project.id, team_id: team.id, for_student: student.id, by_professor: true)%>
      <td class="align-middle">
        <%# form to change avg. score %>
        <%= render 'projects/project_partials/avg_score', prof_eval: prof_eval, project: project, team: team, student: student%>
      </td>
      <% team.evaluations.where(project_id: project.id).where.not(by_student: nil).each do |evaluation| %>
        <% if evaluation.for_student == student.id %>
          <% if !evaluation.score.to_i.zero? && evaluation.score.to_i < 5 %>
            <%# score lesser than 5 %>
            <td class="fw-bold fst-italic table-danger"><%= evaluation.score %></td>
            <td class="fw-bold fst-italic table-danger"><%= evaluation.comment %></td>
            <td class="fw-bold fst-italic table-danger">By <%= Student.find(evaluation.by_student).user.name %></td>
          <% else %>
            <td><%= evaluation.score %></td>
            <td><%= evaluation.comment %></td>
            <td>By <%= Student.find(evaluation.by_student).user.name %></td>
          <% end %>
        <% end %>
      <% end %>
    </tr>
  <% end %>
<% end %>

app/views/projects/project_partials/_show_teams_table.erb
<table class="table table-light table-striped table-bordered rounded mt-3 w-75 m-auto">
  <thead class="text-center">
    <tr>
      <th  scope="col" class="col-2">Team</th>
      <th  scope="col" class="col-4" colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="4"><%# for aesthetic purposes %></td>
    </tr>
    <% counter = 1 %>
    <% project.project_teams.each do |project_team| %>
      <% team = Team.find(project_team.team_id)%>
      <tr>
        <td class="text-center"> <%= team.team_name %></td>
        <td class="text-center"><%= link_to 'View Team', team %></td>
        <td class="text-center">
          <%= link_to 'Edit Team', "#updateTeam#{counter}", "data-bs-toggle":"collapse", "aria-expanded":"false", "aria-controls":"updateTeam#{counter}" %>
        </td>
        <td class="text-center"><%= link_to 'Remove Team', project_remove_team_path(project_id: project.id, team: team, course_id: course_id), method: :delete, data: { confirm: 'Are you sure you want to remove this team? Removing the team will also delete all evaluations assigned to this team.' } %></td>
      </tr>
      <tr>
        <td colspan="4">
          <div class="collapse" id="updateTeam<%= counter %>">
            <div class="card card-body">
              <%= render '/courses/navigation_partials/update_team_form', team: team %>
            </div>
          </div>
        </td>
      </tr>
      <% counter += 1 %>
    <% end %>
  </tbody>
</table>

app/views/projects/project_partials/_student_evaluation_row.erb
<% if !evaluation.score.to_i.zero? && evaluation.score.to_i < 5 %>
  <%# score lesser than 5 %>
  <tr class="fw-bold fst-italic table-danger">
    <td><%= evaluation.score %></td>
    <td><%= evaluation.comment %></td>
    <td>By <%= Student.find(evaluation.by_student).user.name %></td>
  </tr>
<% else %>
  <tr>
    <td><%= evaluation.score %></td>
    <td><%= evaluation.comment %></td>
    <td>By <%= Student.find(evaluation.by_student).user.name %></td>
  </tr>
<% end %>

app/views/projects/project_partials/_update_project_form.erb
<%= form_with(url: project_update_path(id: project.id, project_id: project.id, course_id: project.course_id), method: 'patch', model: project) do |form| %>
  <div class="row justify-content-center g-3">
    <div class="col-xl-7 col-9">
      <%= form.text_field :project_name, class:"form-control form-control-lg", placeholder:"Course Name", value: project.project_name, id:nil, "aria-label":"Course Name" %>
    </div>
    <div class="actions col-xl-2 col-9">
      <%= form.submit "Update", class: "btn btn-lg btn-primary p-2 rounded" %>
    </div>
  </div>
<% end %>