config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :courses do
    get 'index'
    post 'index', to: 'courses#create', as: 'create'
    put 'index', to: 'courses#update', as: 'update'
    delete 'index', to: 'courses#destroy', as: 'delete'
    get 'navigation'
    post 'navigation', to: 'teams#create', as: 'create_team'
  end
  resources :teams do
    put 'update', to: 'teams#update', as: 'update'
  end
  resources :students do
    put 'edit', to: 'students#update'
  end
  resources :projects do
    get 'add-team', to: 'projects#create_project_team'
    post 'add-team', to: 'projects#create_project_team', as: 'create_team'
    delete 'remove-student', to: 'projects#remove_team', as: 'remove_team'
    get 'update-project', to: 'projects#update'
    patch 'update-project', to: 'projects#update', as: 'update'
    get 'change_average', to: 'projects#set_avg_score'
    patch 'change_average', to: 'projects#set_avg_score', as: 'update_avg'
  end
  resources :evaluations do
  end
  resources :users

  root 'sessions#new'

  get '/search', to: 'students#search'
  post '/search', to: 'students#create'
  # ----------------------- login ----------------------------
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # ------------------------ logout ---------------------------
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  # ----------------------- sign up ----------------------------
  get '/signupstudents', to: 'users#newStudent'
  post '/signupstudents', to: 'users#createStudent'
  get '/signupprofessors', to: 'users#newProfessor'
  post '/signupprofessors', to: 'users#createProfessor'
  # ----------------------- evaluation ----------------------------
  get 'static_pages', to: 'static_pages#dashboard', as: :student_dashboard
  get 'static_pages/view_evaluations', to: 'static_pages#view_evaluations', as: :view_evaluations
  # ----------------------- admin ----------------------------
  post '/:id/search', to: 'students#create'
  post '/addstudent', to: 'students#createFromTeam'

  get '/:id/students/22/edit', to: 'students#create'
  get '/courses/:id/course_navigation', to: 'courses#navigation'
  get '/courses/:id/course_navigation/new_team', to: 'teams#new'
  get '/courses/:id/course_navigation/new_student', to: 'students#new'
  # route to remove student from team - teams/show.html.erb
  delete '/student/:id', to: 'students#destroy', as: 'remove_student'
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

# controller for courses
class CoursesController < ApplicationController
  before_action :set_course, only: %i[update destroy]

  # GET /courses
  # GET /courses.json
  def index
    professors = User.find(current_user.id).professors
    @courses = []
    professors.each do |professor|
      @courses << Course.find(professor.course_id) unless professor.course_id.nil?
    end
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @user = User.find(current_user.id)

    if @course.save
      # tag professor to a new course
      Professor.create user_id: current_user.id, course_id: @course.id
      # delete all professor for this user without a course_id
      @user.professors.all.where(course_id: nil).destroy_all
      flash[:success] = "Course #{@course.course_name} was successfully created."
    else
      # create fails
      flash[:danger] = "Course could not be created. #{@course.errors.full_messages[0]}"
    end
    redirect_to courses_url
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    old_name = @course.course_name
    if @course.update(course_params)
      flash[:success] = "#{old_name} was successfully updated to #{@course.course_name}."
    else
      flash[:danger] = "#{@course.course_name} could not be updated. #{@course.errors.full_messages[0]}"
    end
    redirect_to courses_url
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    flash[:success] = "#{@course.course_name} was successfully deleted."
    @course.destroy
    redirect_to courses_url
  end

  def navigation
    # @team = Team.new
    @course = Course.find(params[:id])
    @teams = Team.all.where(course_id: @course.id)
    # get students in the course
    @students = []
    Course.find(@course.id).teams.all.each do |team|
      team.students.each do |student|
        @students << student
      end
    end
    # create evaluations if not already created
    create_evaluations_for_all_project_teams(params[:id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:course_num, :course_name)
  end
end

app/views/courses/_create_course.html.erb
<%= form_with(model: @course, class:"row") do |form| %>
  <div class="col">
    <input name="course[course_name]" type="text" class="form-control form-control-lg" placeholder="Course Name">
  </div>
  <div class="col">
    <input name="course[course_num]" type="text" class="form-control form-control-lg" placeholder="Course Number">
  </div>
  <div class="actions col">
    <%= form.submit "Create Course", class: "btn btn-primary btn-lg p-2 rounded" %>
  </div>
<% end %>

app/views/courses/_index_create_course_form.html.erb
<%= form_with(url: create_courses_path, model: @course, class:"row") do |form| %>
  <div class="col">
    <input name="course[course_name]" type="text" class="form-control form-control-lg" placeholder="Course Name">
  </div>
  <div class="col">
    <input name="course[course_num]" type="text" class="form-control form-control-lg" placeholder="Course Number">
  </div>
  <div class="actions col">
    <%= form.submit "Create Course", class: "btn btn-primary btn-lg p-2 rounded" %>
  </div>
<% end %>

app/views/courses/_navigation_teams_table.erb
<table class="table table-light table-striped table-bordered rounded mt-3">
  <thead class="text-center">
    <tr>
      <th  scope="col" class="col-2">Teams</th>
      <th  scope="col" class="col-2"></th>
      <th  scope="col" class="col-2"></th>
    </tr>
  </thead>
  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td class="text-center"> <%= team.team_name %></td>
        <td class="text-center"><%= link_to 'View Team', team %></td>
        <td class="text-center"><%= link_to 'Delete Team', team, method: :delete, data: { confirm: 'Are you sure? Destroying the team will also destroy all students assigned to this team.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/index.html.erb
<h1 class="my-5 text-center">Courses for <%= current_user.name %></h1>
<%= render '/courses/index_partials/create_course_form' %>
<div class="table-responsive mt-4">
  <table class="table table-light table-striped table-bordered rounded text-center align-middle">
    <thead>
      <tr>
        <th colspan="1">Course Name</th>
        <th colspan="4"> Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td colspan="5"><%# for aesthetic purposes %></td>
      </tr>
      <% counter = 1 %>
      <% @courses.each do |course| %>
        <tr>
          <td class="align-middle"><%= course.course_name %></td>
          <td class="align-middle"><%= link_to 'Enter Course', navigation_courses_path(id: course.id) %></td>
          <td class="align-middle"><%= link_to 'View Projects', projects_path(course_id: course.id) %></td>
          <td class="align-middle">
            <%= link_to 'Edit Course', "#updateCourse#{counter}", "data-bs-toggle":"collapse", "aria-expanded":"false", "aria-controls":"updateCourse#{counter}" %>
          </td>
          <td class="align-middle"><%= link_to 'Delete Course', delete_courses_path(id: course.id), method: :delete, data: { confirm: 'Are you sure? Deleting this course will also delete all related data, including students and teams.' } %></td>
        </tr>
        <tr>
          <td colspan="5">
            <div class="collapse" id="updateCourse<%= counter %>">
              <div class="card card-body">
                <%= render '/courses/index_partials/update_course_form', course: course%>
              </div>
            </div>
          </td>
        </tr>
        <% counter += 1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/courses/navigation.html.erb
<h1 class="text-center my-5"> <%= @course.course_name %> </h1>
<%#----------------------------- Teams Table -----------------------------%>
<%= render '/courses/navigation_partials/create_team_form' %>
<div class="table-responsive mt-3">
  <%= render '/courses/navigation_partials/teams_table'%>
</div>
<%#----------------------------- Students Table -----------------------------%>
<%= render '/courses/navigation_partials/search_student'%>
<%# show the select team only if email is found %>
<% if !params[:found].nil? && params[:found] = "success" %>
  <%= render '/courses/navigation_partials/select_student_team', student: Student.find(params[:student_id]) %>
<% end %>
<div class="table-responsive">
  <%= render '/courses/navigation_partials/students_table'%>
</div>
<form action=<%=courses_path%>>
  <input class="btn btn-primary btn p-2 rounded mb-5 col-md-1 col-12" type="submit" value="&#8592; Back" />
</form>